### ISSUE TITLE
Add Github Topics

### ISSUE THREAD

**Issue by bcremer** [synonymous1984/SwAlgolia#12]
Github recently introduced "Topics": <https://github.com/blog/2309-introducing-topics>.

![image](https://cloud.githubusercontent.com/assets/55820/22497681/acd0fe46-e853-11e6-9faf-5d36fd0eb45c.png)

I would like to suggest the topics "shopware" and "shopware-plugin" for this repo.

**Comment by synonymous1984** [comment]
Added shopware and algolia topics
