### ISSUE TITLE
Add License information

### ISSUE THREAD

**Issue by bcremer** [synonymous1984/SwAlgolia#2]
Let me first say thank you, this is a great Project :+1: 

At the moment no License information are provided.
You should clarify which license applies for potential users and contributors to this project.

**Comment by shyim** [comment]
@synonymous1984 MIT?

**Comment by synonymous1984** [comment]
I´ve already asked but nobody could tell me which license we are allowed to use... Does the os plugin also to be under AGPL @bcremer ?

**Comment by bcremer** [comment]
No they don't have to be AGPL.

I much prefer MIT myself, and that's also the license we at shopware use for most plugins like: https://github.com/shopwareLabs/SwagPaymentPaypal

**Comment by synonymous1984** [comment]
I´ve taken AGPL now. The reason is, that AGPL forces forkers to also provide it as open source which MIT does not.

**Comment by bcremer** [comment]
Please consider the license carefully, especially with AGPL you are not allowed to change the license later on without the agreement of every single contributor. 
If you plan to fork this plugin later on in a commercial product MIT is beneficial to you.

**Comment by synonymous1984** [comment]
Thanks @bcremer - what do you think contribs @shyim @jochenmanz?

**Comment by jochenmanz** [comment]
I would prefer MIT over AGPL. @shyim, what do you think?

**Comment by shyim** [comment]
also

**Comment by synonymous1984** [comment]
I´m not sure if I´m a friend of MIT license for this plugin. MIT means that **anyone** can take our project, add a small piece of additional functionality, **encode it and sell it**. GPL/AGPL prohibits this cause everybody who uses the source has to offer the code also under the AGPL license and open to the public. For end users it doesn´t make any difference, cause this piece of software is very specific and not abstract to be used as part in another software.

I already made bad experiences with plugin´s I have offered under the MIT for other ecommerce systems.

Please let me know your ideas why MIT is better for this project then GPL/AGPL or other licenses.
